spring:
  application:
    name: expense_database

  datasource:
    # Use environment variables when available, otherwise fall back to sensible defaults for local dev
    url: ${DB_URL:jdbc:mysql://localhost:3306/expense_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:Spencer}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}



jwt:
  secret: C1E67BF842C9AE41916D57FB7CFCC
  expiration: 86400000

file:
  upload-dir: ./uploads/receipts

